# Generated by Django 4.0.6 on 2022-07-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='icon',
            field=models.FileField(blank=True, upload_to='icons/%Y/%m/%d/', verbose_name='Иконка'),
        ),
    ]
