# Generated by Django 4.0.6 on 2022-08-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_feedback_alter_articles_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
